#!/bin/bash
echo "Wait for mysql service to be ready"
wait-for-it.sh -t 0 dbserver:3306
sleep 20

echo "Get Database ready"
php bin/console doctrine:database:create --if-not-exists
php bin/console doctrine:schema:update --force

echo "Clear Production Cache"
php bin/console cache:clear --env=prod --no-debug
php bin/console assets:install  --env=prod
php bin/console assetic:dump --env=prod

echo "Changing permissions"
chown -R www-data.www-data /var/www/html

echo "Start fpm service"
php-fpm

